### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [Unknown82/projekt-1-unger#1]
1.https://github.com/Unknown82/projekt-1-unger/blob/200dbd8a46416182897a5565f322018d0f77b700/index.html#L170-L171
Если у `label` указано `for="some-input"`, у `input` нужно указывать `id="some-input"`

2. Стилизация чекбокса http://dimox.name/custom-checkboxes-and-radio-buttons-using-css-only/ 

3. https://github.com/Unknown82/projekt-1-unger/blob/200dbd8a46416182897a5565f322018d0f77b700/index.html#L270-L272
Лучше убрать `h4`, поскольку этот тег отвечает за заголовки

4. https://github.com/Unknown82/projekt-1-unger/blob/200dbd8a46416182897a5565f322018d0f77b700/index.html#L536-L540
Форма уезжает на широком мониторе, потому что задано позиционирование `left`. Я бы переделал эту часть след. образом:
```
div.kont-form-wrapper
  form.kont-form
    h3.kont-form__title
```
И на wrapper повесить позиционирование, но без фона и внутри него выровнять форму, которой задать черный фон

5. https://github.com/Unknown82/projekt-1-unger/blob/200dbd8a46416182897a5565f322018d0f77b700/css/main.css#L897
На 1024 верстка разваливается. Нужно либо сделать доп. брейкпойнты 768-1440, либо установить верхнюю границу в 1440

**Comment by sffr-dev** [comment]
1. https://github.com/Unknown82/projekt-1-unger/blob/5b393a686b6ccf2176312559d844ea7de3cb9389/index.html#L171
`id` должен быть уникальным. Не может быть двух одинаковых `id`

2. пп 2 и 5 не сделаны.

**Comment by sffr-dev** [comment]
1. https://github.com/Unknown82/projekt-1-unger/blob/95b8aca7ea180c7ffd5ab001b7a2299cd132863b/css/main.css#L185
https://github.com/Unknown82/projekt-1-unger/blob/95b8aca7ea180c7ffd5ab001b7a2299cd132863b/css/main.css#L1133-L1134
Вот эти стили на мобильной верстке добавляют горизонтальную прокрутку

2. https://github.com/Unknown82/projekt-1-unger/blob/95b8aca7ea180c7ffd5ab001b7a2299cd132863b/index.html#L461
https://github.com/Unknown82/projekt-1-unger/blob/95b8aca7ea180c7ffd5ab001b7a2299cd132863b/index.html#L575
https://github.com/Unknown82/projekt-1-unger/blob/95b8aca7ea180c7ffd5ab001b7a2299cd132863b/index.html#L632
В `svg` сохраняем только иконки и векторные изображения

3. https://github.com/Unknown82/projekt-1-unger/blob/95b8aca7ea180c7ffd5ab001b7a2299cd132863b/css/main.css#L1134-L1135
Из-за этого картинка на 720px перекрывает форму

**Comment by Unknown82** [comment]
<img src="img/clients1.svg" alt="client"> 

clients.svg Это и есть иконка

**Comment by Unknown82** [comment]
img/clients1.svg

**Comment by sffr-dev** [comment]
1. https://github.com/Unknown82/projekt-1-unger/blob/2d5de946aea6b0a7c4fc53a15807348be0939a68/css/main.css#L1090
Давайте сюда добавим `max-width: 400px;` и выровняем весь блок по центру. Сейчас на 768 выглядит плохо

2. 
![image](https://user-images.githubusercontent.com/57518708/78215705-d2f47380-74c0-11ea-9b98-4c1406c27436.png)
![image](https://user-images.githubusercontent.com/57518708/78215805-164ee200-74c1-11ea-8e03-4baa785fa77c.png)
Вот это тоже нужно поправить

Последние правки и ставлю вам отлично

**Comment by sffr-dev** [comment]
Вот тут https://github.com/Unknown82/projekt-1-unger/blob/5bb4b85ddf65d081f9ff1f361c532b1260d3fef0/css/main.css#L1093-L1095 нужно добавить `max-width: 100%;`
